[project]
name = "phys"
version = "0.1.0"
dependencies = ["numpy", "polars"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
venv = ".venv"
venvPath = "."
